### ISSUE TITLE
List issues with MinionList

### ISSUE THREAD

**Issue by mchugh19** [SUSE/saltstack-netapi-client-java#104]
Perhaps I'm doing something wacky, but I'm unable to get the MinionList targetType to work with a list input. 

```java
String commaSeparated = "jessievm";
List<String> mytargetList = Arrays.asList(commaSeparated);
Target finaltarget = new MinionList(mytargetList);
scheduledJob = client.startCommand(finaltarget, myfunction, saltArguments, kwArgs);
```

Passing in a List seems to result in not sending a message to the salt master, thus leaving an a null ScheduledJob causing havoc. Passing in a plain "jessievm" string seems to work as expected.

**Comment by lucidd** [comment]
The `commaSeperated` variable name suggests that you have a string with comma seperated values is that right? If so that won't work like that.
The `MinionList` can be created in 3 different ways.

```java
      //With individual values
      MinionList minions = new MinionList("minion1", "minion2", "minion3");
      System.out.println(minions.getTarget());

      //With a list of strings
      List<String> stringList = new ArrayList<>();
      stringList.add("minion4");
      stringList.add("minion5");
      stringList.add("minion6");
      minions = new MinionList(stringList);
      System.out.println(minions.getTarget());

      //With an array of strings
      String[] stringArray = new String[]{"minion7", "minion8", "minion9"};
      minions = new MinionList(stringArray);
      System.out.println(minions.getTarget());
```
Should output:
```
[minion1, minion2, minion3]
[minion4, minion5, minion6]
[minion7, minion8, minion9]
```

If you have a comma separated list and want to use that you have to turn it into an array or list first for example by using `split`.

```java
      String commaSeparated = "minion10,minion11,minion12";
      String[] separatedIntoArray = commaSeparated.split(",");
      minions = new MinionList(separatedIntoArray);
      System.out.println(minions.getTarget());
```

Should output: 

```
[minion10, minion11, minion12]
```

Also consider moving to the new `callSync` / `callAsync` functions for executing functions. If you need help with that just drop us a line and we can provide you examples.
Not all functions are supported yet but if you tell us what functions and modules you are interested in we can make sure to include those in the next release.

**Comment by mchugh19** [comment]
I think that's what I'm doing, but I'm still running into problems. The comma separated list was simply used to populate the List<String>. So it's really a List that's being sent to the MinionList.

```java
Target finaltarget;
String commaSeparated = "jessievm, stratos.kix.";
List<String> mytargetList = Arrays.asList(commaSeparated);
System.out.println(mytargetList); //[jessievm, stratos.kix.]
finaltarget = new MinionList(mytargetList);
scheduledJob = client.startCommand(finaltarget, myfunction, saltArguments, kwArgs);
System.out.println(scheduledJob.getJid()); // NULL
```

I'll investigate migrating to callSync/callAsync. Thanks for the head's up.

**Comment by lucidd** [comment]
I think the problem is the use of `Arrays.asList`. The only thing it does is put your string into a list. It does not split it in any way you have to use something like the String split method as described in my previous answer. Also make sure your minion names don't have whitespaces after you split the string otherwise it will not match.

```java
        Target finaltarget;
        String commaSeparated = "jessievm,stratos.kix.";
        List<String> mytargetList = Arrays.asList(commaSeparated.split(","));
        System.out.println(mytargetList);
        finaltarget = new MinionList(mytargetList);
        ScheduledJob scheduledJob = authorized.startCommand(finaltarget, "test.ping", null, null);
        System.out.println(scheduledJob.getJid());


        LocalAsyncResult<Boolean> pingJob = authorized.callAsync(Test.ping(), finaltarget);
        System.out.println(pingJob.getJid());
```

**Comment by mchugh19** [comment]
In further testing, it might be the "stratos.kix." string which is causing the issues. 

```java
Target finaltarget;
String commaSeparated = "stratos.kix.";
List<String> mytargetList = Arrays.asList(commaSeparated.split(","));
System.out.println(mytargetList); //[stratos.kix.]
finaltarget = new MinionList(mytargetList);
scheduledJob = client.startCommand(finaltarget, myfunction, saltArguments, kwArgs);
System.out.println(scheduledJob.getJid()); // NULL
```

Where as running the same thing with a different target returns better results.
```java
Target finaltarget;
String commaSeparated = "jessievm";
List<String> mytargetList = Arrays.asList(commaSeparated.split(","));
System.out.println(mytargetList); //[jessievm]
finaltarget = new MinionList(mytargetList);
scheduledJob = client.startCommand(finaltarget, myfunction, saltArguments, kwArgs);
System.out.println("Running jid: " + scheduledJob.getJid()); // Running jid: 20150904115750474658
```

Crazily enough, I've also run into some funky conditions causing the scheduledJob variable to return badly:
targetlist [jessievm]
Running jid: 20150904115646754909
FATAL: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 79 path $.info[0].Target
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 79 path $.info[0].Target
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
...


The line that it's choking on is:
```java
jobResults = client.getJobResult(scheduledJob)
```
which came right after the "Running jid: " line from the jessievm example above. Recompiling and re-running caused this issue to resolve itself. So maybe I've got something funky cached, but I've seen this a few times now, so thought it worth mentioning.

**Comment by lucidd** [comment]
Are you sure the minion name `stratos.kix.` is right? i've never seen a minion name ending on . so i'm not sure if this is valid or a typo or something. Does it work if you use the `salt` command to execute something on the minion with this name?

**Comment by mchugh19** [comment]
Ha! Sorry for the noise, you are absolutely right. My domain at home I use for testing is .kix. Since it doesn't resolve, I have to enter the final . to keep webbrowsers from attempting to turn that term into a search. However, in the case of salt, its hostname is without the final dot.

After updating to an actual salt minion id name, everything works as expected. Thanks for working through this, and sorry for bugging you :)

**Comment by lxx3061313** [comment]
I still have the problems describ above.
FATAL: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 79 path $.info[0].Target
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 79 path $.info[0].Target
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)

I think the reason is that 
the json result from client.getJobResult(scheduledJob) can't match the object com.suse.salt.netapi.results.ResultInfo

the json result is:
{
  "info": [
    {
      "Function": "test.ping",
      "jid": "20170323000416629667",
      "Target": [
        "app10.hp.sp.tst.bmsre.com",
        "lixiaoxiong-IdeaPad-U330p"
      ],
      "Target-type": "list",
      "User": "mossad",
      "StartTime": "2017, Mar 23 00:04:16.629667",
      "Arguments": [],
      "Minions": [
        "app10.hp.sp.tst.bmsre.com",
        "lixiaoxiong-IdeaPad-U330p"
      ],
      "Result": {
        "app10.hp.sp.tst.bmsre.com": {
          "return": true
        }
      }
    }
  ],
  "return": [
    {
      "app10.hp.sp.tst.bmsre.com": true
    }
  ]
}

and ResultInfo is:
@SerializedName("Function")
    private String function;

    @SerializedName("StartTime")
    private StartTime startTime;

    @SerializedName("Arguments")
    private List<Object> arguments;

    @SerializedName("Minions")
    private final HashSet<String> minions = new HashSet<>();

    @SerializedName("User")
    private String user;

    @SerializedName("Target")
    private String target;
