### ISSUE TITLE
Clarify usage of kwargs

### ISSUE THREAD

**Issue by lucidd** [SUSE/saltstack-netapi-client-java#49]
@renner can you clarify what the `kwargs` parameter in methods like `startCommand` is used for? As far as i can tell it only adds additional properties to the JSON but i don't know what i would use that for.

Initially i thought it would be to pass parameter to the remote function by name instead of by position but after a bit of research i found out that the `kwarg` property is used for that.

**Comment by renner** [comment]
Good catch, this actually looks like a bug around `ClientUtils.makeJsonData()`: All the `kwargs` that are passed to e.g. `startCommand()` were originally supposed to end up in a JSON property named `kwarg`, which is the one that you are mentioning. The current code just puts them as separate JSON properties named after the keys instead.

Feel free to send a pull request in order to fix that, otherwise I can have a look as soon as I find the time. Thanks for reporting this issue!

**Comment by lucidd** [comment]
Thanks for the clarification i will submit a PR to fix it.
