### ISSUE TITLE
Stability of SaltStack API

### ISSUE THREAD

**Issue by hustodemon** [SUSE/saltstack-netapi-client-java#57]
Hi everyone,
I was just browsing through SaltStack sources and I was thinking about
their API we consume. One particular thing worries me a bit: how much stable is
it?

Usually when one works with any kind of API, he/she assumes it is kind of
stable (ideally between major versions of the project). When looking at the
sources of SaltStack, I found out that their API is just a thin layer that
"translates" requests to their backend. And not only to backend - in some cases
the API relies on external libraries as well: for instance, in case of `/stats`
resource, the SaltStack API forwards to the CheeryPy lib.

If the facts above are right, then any minor change in SaltStack backend
or in an API of external library (e.g CherryPy) would affect the SaltStack API
as well. This doesn't completely resemble a reliable interface.

My question is: do they guarantee stable API at least between major
versions? If the answer is yes, which I hope for, then I guess we are fine - I can
imagine we'd just release java clients matching to SaltStack major versions.
Otherwise we're in the trouble as it'd be our role to deal with it and
"stabilize their API". What do you think? Maybe I should directly ask SaltStack
guys as well.

**Comment by isbm** [comment]
Within the version, unlikely. Between the major versions Salt is changing internally (mostly expands, almost keeping backward compatibility). Not sure how it affects APIs though, try testing against it at 2015.2?

But Salt guys _certainly_ should be aware of this library and reference it.

**Comment by moio** [comment]
@hustodemon, I see your concerns. SaltStack in general and this REST API we consume in particular do not have the stability of, say, the typical Apache project. This ecosystem is still pretty new and "bubbling" here and there, so there is a concrete possibility that we'll have to keep our code up-to-date as upstream changes things, and there is also a possibility that our side will become messy at some point.

How we will deal with it (either by producing version-specific flavors of this library or providing a stable API that can accomodate multiple SaltStack changes) pretty much depends on what they do, and how big version changes will be.

Nevertheless keep in mind that despite this library is supposed to be a generic SaltStack API for Java code, it was created for a specific use case, namely the integration of SaltStack into [Spacewalk](http://spacewalkproject.org/) and [SUSE Manager](https://www.suse.com/products/suse-manager/), and that is still the primary aim. Those projects will likely not support a huge range of SaltStack versions, but only the one or two bundled at a certain point in time, so the potential issues you mentioned are less severe from that (admittedly restricted) point of view.

To sum up:
 - your concerns are valid, but they are speculation at this point. We still don't know how SaltStack and its REST API will evolve, so we might or might not have to keep up;
 - I am not sure that planning for upstream changes ahead of time is useful at this point. We will see how much these APIs actually change and react with the most appropriate technical solution when it happens;
 - in case we get big trouble because of wild differences among a wide number of versions, we can still opt to support only the subset needed for Spacewalk and SUSE Manager. It's not an ideal approach, but still it will work for the original purpose, and community can help in supporting other versions;
 - this being a GitHub issue, I would like to see discussion evolve towards an "actionable" direction. Is there something we want to change in the code at this point? Are there any concrete steps we can take to improve the situation?

Thanks for the discussion,

moio

**Comment by moio** [comment]
@hustodemon, I saw no reply from you in the last week, so I am closing this. Feel free to reopen it anytime if you have further comments.

**Comment by hustodemon** [comment]
Yes, I wanted to close it anyway. The fact Spacewalk/SUSE Manager will support only some versions of SaltStack answers the issue.

(Off-topic: About your last point: is there any other way devels of this project can exchange messages? I see no mailing lists/IRC.... I only created the issue because I saw no other way to ask about this concern.)

**Comment by moio** [comment]
@hustodemon, sure! The quickest way to reach us is on `#spacewalk` FreeNode. Feel free to join anytime!
