### ISSUE TITLE
websocket interface

### ISSUE THREAD

**Issue by winglet** [SUSE/saltstack-netapi-client-java#79]
Hi all.
So, I've been trying to set up and connect a toy netapi client to a saltapi websocket. My understanding (please correct me if I'm wrong) is that websockets in saltapi are implemented by rest_tornado* (http://salt-api.readthedocs.org/en/latest/ref/netapis/all/saltapi.netapi.rest_tornado.html) which I installed in my saltstack POC installation. 

I managed to connect allright on the server itself (just an ubuntu VM) with a mad-max kind of client (https://github.com/winglet/code-garage/tree/master/saltstack-netapi-garage) but when I'm trying to replicate that with a simple java websockets implementation I get a 404 response from salt-api daemon which on the java client translates to a handshake exception.

I could possibly research this a bit further before dumping logs etc here but the main question right now I guess is whether this direction (salt-api websockets that is) is of any interest to the netapi project.

* This is not clear in the salt-api online documentation.

**Comment by moio** [comment]
@winglet, I guess the main question here would be, would this improve the library functionality?

We already have an endpoint to to `events`, which as stated by rest_tornado documentation offers similar functionality:

> Functionality provided by this endpoint is similar to the /events end point.
http://salt-api.readthedocs.org/en/latest/ref/netapis/all/saltapi.netapi.rest_tornado.html

So my answer would be yes, this might be interesting, but only if this improves over the current `events` endpoint in some way that justifies the installation of a further component on the server.

Currently I am not sure if this is the case or not.

**Comment by lucidd** [comment]
@moio @winglet Since i don't see how we can solve #63 it would be really interesting if this can replace the sse `/events` endpoint completely without having the same problems of not being able to cancel a read to shutdown the connection from the client side.

**Comment by moio** [comment]
@lucidd, another possibility would be to report the Jersey bug upstream or even propose a fix there, or replacing Jersey with some other implementation.

I have no idea how hard those options are, but I am not too happy to require two separate APIs on the Salt server and add a moving part. If the WebSocket option can do things we can't do otherwise OK, but if it is equivalent I am not sure it is worth it.

**Comment by winglet** [comment]
The curl/Python toy 'client' seems to work fine with rest_tornado salt module but I still cannot make it with a Java/websockets client (in short I'm hitting a Handshake error which in turn stems from server replying with 404 when trying to set up the websocket). I'm still researching it (not much info around and this is going slowly - side job) but in the process I hit a thread where it seems that the rest_cherrypy might be obsoleted over time https://github.com/saltstack/salt/issues/13698 

Other than that I -too- don't see any extra features in tornado except maybe for the formatted_events endpoint (trivial though). In fact I think that tornado is one endpoint short (`/stats`).

**Comment by whiteinge** [comment]
Quick note: the `rest_tornado` netapi module is not 100% API compatible with the `rest_cherrypy` netapi module at this time. I will not deprecate `rest_cherrypy` until moving from one to the other is seamless. I have no near-term plans to begin that work and so I estimate the `rest_cherrypy` driver will continue to be the officially-supported REST API for the rest of the year. When we make that switch client libraries such as this one should not notice the difference.

Rephrased: I recommend developing against the `rest_cherrypy` netapi module at this time.

@winglet to websocket support: both `rest_tornado` and `rest_cherrypy` netapi modules have websocket endpoints. Both implementations were bolt-ons for the now defunct Halite project. I do not know that either implementation was fully completed or that either are in-use anywhere. Please feel to poke at that code yourself or file issues on the main Salt repo about that.

I wish I had advice to offer on how best to implement Server Sent Events stream support (the `/events` URL) in Java, but if there's anything else I can help with (testing, spec compliance, etc), please do feel free to ping me directly.

**Comment by moio** [comment]
@whiteinge, thanks for sharing, this makes planning our future work a lot easier!

From my perspective using WebSockets is simply an implementation detail of a possible solution to issue #63, as IIUC it is not a feature per se. As @whiteinge suggested, it is probably wise to keep using `rest_cherrypy` for the time being, so the `salt.netapi.rest_cherrypy.app.WebsocketEndpoint` class seems to be the right candidate. Other possibilities would be fixing the current version (at the Jersey level if necessary) or reimplementing it with a different SSE library.

It would still be interesting to get an idea of how many methods fail by swapping `rest_cherrypy` with `rest_tornado`, but I guess this is a different issue.

@winglet, @lucidd: do you agree? Is it OK to close this issue and maybe create a new one for `rest_tornado` research, or should we simply rename this one to make the intention clearer?

**Comment by winglet** [comment]
@moio Yes, I'm OK with it.
PS: Thanks for asking my opinion guys - provided I'm 2 weeks old in here that was impressive :smile:

**Comment by lucidd** [comment]
@moio yes is think we can close this issue and open one for experimenting with the `rest_cherrypy` `/ws` endpoint. Like you said unless the websocket endpoint offers more functionality/information its merely an implementation detail. One think we should think about is if we need both SSE and Websocket if we can cover both with one then i don't see a reason to add another library just to provide the same information. I think Websockets are the better bet here since they can do more and if `rest_cherrypy` decides to make use of their bidirectional nature then we are already covered.

**Comment by whiteinge** [comment]
The SSE stream from `rest_cherrypy` is mature and frequently used by our customers and by SaltStack; it will continue to see development and maintenance. The websockets endpoint is currently status unknown and any near-term effort there will need to be community driven because we do not have a current business need for it nor do we have spare development cycles to throw at it (at this time). I, personally, think it would be an awesome thing to have fully fleshed out but I don't have the time to work on it myself. :weary:

**Comment by winglet** [comment]
@whiteinge Hi Seth. Thanks for the remarks. I got a bit further with this. I recapped the issue I'm hitting here: https://github.com/saltstack/salt/issues/24730

**Comment by moio** [comment]
Closing this issue as per above comments, thanks everyone for the discussion!
