### ISSUE TITLE
Support job status for unfinished jobs

### ISSUE THREAD

**Issue by mchugh19** [SUSE/saltstack-netapi-client-java#83]
When kicking off a job, the saltapi response includes a minion array listing minion names and the job results. If the job is long running,  you can iterate through the number of minions that are targeted, and spin waiting for all to return. 

Please support querying this minion listing.

**Comment by mchugh19** [comment]
To clarify, when you send a long running job to salt, like in this example using sleep:
```json
[{
    "arg": ["sleep 14; echo testing"],
    "client": "local",
    "expr_form": "glob",
    "fun": "cmd.run",
    "tgt": "dynocache2*"
}]
```
you get back a JID. When you lookup the job using that JID, you get back:

```json
{
    "info": [{
        "Function": "cmd.run",
        "jid": "20150704153935653922",
        "Target": "dynocache2*",
        "Target-type": "glob",
        "User": "jenkins",
        "StartTime": "2015, Jul 04 15:39:35.653922",
        "Arguments": ["sleep 14; echo testing"],
        "Minions": ["dynocache2v2.cws.dpdcn.unt.edu", "dynocache2v1.cws.dpdcn.unt.edu"],
        "Result": {}
    }],
    "return": [{}]
}
```

Note that the result, and return keys are empty, but the minion key is populated with the hosts we are waiting on. Thus, even though the job has not yet finished, we are able to see that we are waiting for two hosts in this example.

Once the job has completed, looking up that JID now returns:
```json
{
    "info": [{
        "Function": "cmd.run",
        "jid": "20150704153935653922",
        "Target": "dynocache2*",
        "Target-type": "glob",
        "User": "jenkins",
        "StartTime": "2015, Jul 04 15:39:35.653922",
        "Arguments": ["sleep 14; echo testing"],
        "Minions": ["dynocache2v2.cws.dpdcn.unt.edu", "dynocache2v1.cws.dpdcn.unt.edu"],
        "Result": {
            "dynocache2v2.cws.dpdcn.unt.edu": {
                "return": "testing"
            },
            "dynocache2v1.cws.dpdcn.unt.edu": {
                "return": "testing"
            }
        }
    }],
    "return": [{
        "dynocache2v2.cws.dpdcn.unt.edu": "testing",
        "dynocache2v1.cws.dpdcn.unt.edu": "testing"
    }]
}
```

Notice here we have both the return key and the result key populated with our expected results so we can tell that both of our hosts have come back. 

Currently, running a job via the startCommand method returns the jid as expected. But looking up the jid for a long running job does not give back the full response from the saltmaster, but only the return key. Thus, for a long running job it is not possible to easily tell if all minions have returned. 

It would be helpful if querying the jid returned enough info to tell if we are still waiting for any minions to return.

**Comment by AdamMajer** [comment]
This is work-in-progress. I would appreciate some feedback since this issue can be fixed in many ways.

The approach in this patch adds JobsState.PENDING enum that is artificially added to results set for minions that have yet to return. This may be a little blunt. API is not changed, but user now has to check if job is pending before processing minion's output.

An alternative is to parse `info` and disregard `return`. `info["Result"]` seems to contain the same data as in `return`, though in slightly different order. Returning Info instead of a result map would definitely result in API changes, but it would allow for much more flexible interface for job results.

What do you guys think?

**Comment by lucidd** [comment]
@AdamMajer hey first of all thanks for your effort. I like your idea with the enum of different states a job can be in but i don't think we need to add it to the data itself. Instead i think it can be just a method that calculates the state of a minion on the fly when you ask for it. 

One thing that would be interesting if we can differentiate between `Pending` (minion is still working on it) and `NoResponse` (minion is down / not available).

An other solution would be to have a method for getting a result for a specific minion out of the info. That method would return `Optional<T>` since the result may not be available yet.

Don't think to hard about keeping the API as it is. We are redoing a lot of it right know in https://github.com/lucidd/saltstack-netapi-client-java/tree/experiments (very experimental and messy branch right know). That means for querying job results we will use the functions here [runner.jobs](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#module-salt.runners.jobs).
`list_job` and `print_job` both return data similar to what is in `info` so your solution should still apply to that.

**Comment by AdamMajer** [comment]
Sounds good. Then the way to go is to parse and return interface to the `info` structure. `Pending` state can be calculated on the fly there. It's definitely more flexible approach than stuffing state enum in results.

It seems that salt-api (http://salt/jobs/<jid> call) simply dumps the contents of `runner.jobs.list_job` and `lookup_jid` for output. This means getting results through `Info` should be the way to proceed. I'll implement this then as it looks it will be usable even with your modifications.

**Comment by AdamMajer** [comment]
I've updated job result parsing. The first patch https://github.com/AdamMajer/saltstack-netapi-client-java/commit/9e3c4be9bc6a751fba746715ebb9214b924a17fa adds support for parsing the `info` part of result structure. This should also fit nicely with @lucidd 's work using 
[runner.jobs.](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#module-salt.runners.jobs) print_job (or list_job) API.

I'm using `results_cache` in `ResultInfo` structure so getResults() is only linear on first invocation. I'm not aware of any "finished parsing" hooks in Gson to process this structure right after parsing, and it's probably not a good idea to parse it every single time someone calls getResults(). And returning `raw_results` makes user's API unnecessarily messy.

Looking at `ResultInfo.getResult(String)`, I could probably make that function more efficient by not calling `containsKey` - 2 key lookups are unnecessary.

The 2nd part of the patch, https://github.com/AdamMajer/saltstack-netapi-client-java/commit/b571b3bada0afa5b12c5b84c2360a0dba44080af , ports getJobResult() functions to use the new API. This makes RETVALS json parser unused..

Should `SaltStackClient.getJobResult()` be removed/replaced completely by `getJobResultInfo()`?

Comments are welcome.

If there are no objections, I'll add documentation and make a pull request.

**Comment by lucidd** [comment]
I'm not completely convinced by the states yet since the `pending` state is not really accurate. We don't really know if the minion is still executing or if the minion never got the job. I think having the method returning the result of a minion with `Optional` is enough since you can easily call `isPresent` to get the same information the states would cover now.

**Comment by AdamMajer** [comment]
I think this issue can now be closed.

**Comment by lucidd** [comment]
closing this since this feature is now supported as of #93 and #94
